// react-workspace/projects/test-react-v17/src/examples/ModusFileDropZoneExamples.tsx
import { ModusFileDropzone } from '@trimble-oss/modus-react-components';

export default function ModusFileDropzoneExamples() {
  return (
    <>
      <h3>File upload dropzone</h3>
      <ModusFileDropzone
        aria-Label="dropzone"
        description="File dropzone description"
        dropzone-Height="175px"
        dropzone-Width="400px"
        label="Dropzone Label"
        multiple={true}
        onFiles={(event) => {
          const [files, error] = event.detail;
          alert(`Files Uplaod: ${files.map((f) => f.name).toString()}`);
        }}></ModusFileDropzone>
    </>
  );
}

// angular-workspace/test-ng15/src/examples/modus-file-dropzone-examples/modus-file-dropzone-examples.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'modus-file-dropzone-examples',
  template: `
    <h3>File Upload Dropzone</h3>
    <modus-file-dropzone
      aria-Label="dropzone"
      description="File dropzone description"
      dropzone-Height="175px"
      dropzone-Width="400px"
      label="Dropzone Label"
      multiple="false"
      (files)="handleFiles($event)">
    </modus-file-dropzone>
  `,
})
export class ModusFileDropzoneExamplesComponent implements OnInit {
  handleFiles = (event: any) => {
    const [files, error] = event.detail;
    console.log(files);
    console.log(error);
  };
  constructor() {}

  ngOnInit(): void {}
}
