// react-workspace/projects/test-react-v17/src/examples/ModusModalExamples.tsx
import { ModusButton, ModusModal } from '@trimble-oss/modus-react-components';

export default function ModusModalExamples() {
  return (
    <>
      <h3>Modal</h3>
      <ModusButton
        id="btn-modal"
        color="primary"
        onButtonClick={(e) => {
          const modal = document.querySelector('#modal1');
          if (modal) {
            (modal as HTMLModusModalElement).open();
          }
        }}>
        Open modal
      </ModusButton>
      <ModusModal
        id="modal1"
        header-text="Modal title"
        primary-button-text="Save changes"
        secondary-button-text="Sweet!"
        primary-button-aria-label="Save changes"
        secondary-button-aria-label="Sweet">
        <p>Woo-hoo, you're reading this text in a modal!</p>
      </ModusModal>
    </>
  );
}

// angular-workspace/test-ng15/src/examples/modus-modal-examples/modus-modal-examples.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'modus-modal-examples',
  template: `
    <h3>Modal</h3>
    <modus-button id="btn-modal" color="primary" (buttonClick)="handleButtonClick($event)">Open modal</modus-button>
    <modus-modal
      header-text="Modal title"
      primary-button-text="Save changes"
      secondary-button-text="Sweet!"
      primary-button-aria-label="Save changes"
      secondary-button-aria-label="Sweet"
      [primaryButtonDisabled]="disableButton">
      <p>Woo-hoo, you're reading this text in a modal!</p>
    </modus-modal>
  `,
})
export class ModusModalExamplesComponent implements OnInit {
  disableButton = false;
  openModal = false;
  handleButtonClick = (e: any) => {
    this.openModal = true;
    this.disableButton = true;
  };
  constructor() {}

  ngOnInit(): void {}
}
