// react-workspace/test-react-v19/src/examples/ModusAlertExamples.tsx
import { ModusAlert } from '@trimble-oss/modus-react-components';

export default function ModusAlertExamples() {
  return (
    <>
      <h3>Alert</h3>
      <div className="grid">
        <ModusAlert dismissible message="Dismissible alert"></ModusAlert>
        <ModusAlert message="Error alert" type="error"></ModusAlert>
        <ModusAlert message="Info gray alert" type="info-gray"></ModusAlert>
        <ModusAlert message="Info gray dark alert" type="info-gray-dark"></ModusAlert>
        <ModusAlert message="Success alert" type="success"></ModusAlert>
        <ModusAlert message="Warning alert" type="warning"></ModusAlert>
      </div>
    </>
  );
}

// angular-workspace/test-ng14/src/examples/modus-alert-examples/modus-alert-examples.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'modus-alert-examples',
  template: `
    <h3>Alerts</h3>
    <div class="flex-column">
      <modus-alert message="Info alert (default)"></modus-alert>
      <modus-alert dismissible message="Dismissible alert"></modus-alert>
      <modus-alert message="Error alert" type="error"></modus-alert>
      <modus-alert message="Info gray alert" type="info-gray"></modus-alert>
      <modus-alert message="Info gray dark alert" type="info-gray-dark"></modus-alert>
      <modus-alert message="Success alert" type="success"></modus-alert>
      <modus-alert message="Warning alert" type="warning"></modus-alert>
    </div>
  `,
})
export class ModusAlertExamplesComponent implements OnInit {
  constructor() {}

  ngOnInit(): void {}
}
