// angular-workspace/test-ng15/src/examples/modus-date-picker-examples/modus-date-picker-examples.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'modus-date-picker-examples',
  template: `
    <h3>Date Picker</h3>
    <modus-date-input
      helperText="mmm dd, yyyy"
      label="Single date"
      [allowedCharsRegex]="regex"
      format="mmm dd, yyyy"
      value="2022-12-22"></modus-date-input>
    <modus-date-picker label="Select date range">
      <modus-date-input
        type="start"
        label="Start"
        format="dd-mm-yyyy"
        helper-text="dd-mm-yyyy"
        [allowedCharsRegex]="regex"
        show-calendar-icon="true"
        value="2022-12-22"></modus-date-input>

      <modus-date-input
        type="end"
        label="End"
        format="dd-mm-yyyy"
        helper-text="dd-mm-yyyy"
        [allowedCharsRegex]="regex"
        show-calendar-icon="true"
        value="2022-12-22"></modus-date-input>
    </modus-date-picker>
  `,
})
export class ModusDatePickerExamplesComponent implements OnInit {
  regex = `[\\d,- ]`;
  constructor() {}

  ngOnInit(): void {}
}

// react-workspace/test-react-v19/src/examples/ModusDatePickerExamples.tsx
import { ModusDateInput, ModusDatePicker } from '@trimble-oss/modus-react-components';

export default function ModusDatePickerExamples() {
  return (
    <>
      <h3>Date picker</h3>
      <div className="grid">
        <ModusDateInput
          helper-text="mm/dd/yyyy"
          label="Single date"
          allowed-chars-regex="[\d\/]"
          format="mm/dd/yyyy"
          value="2022-12-22"></ModusDateInput>

        <ModusDatePicker label="Select date range">
          <ModusDateInput
            type="start"
            label="Start"
            format="dd-mm-yyyy"
            helper-text="dd-mm-yyyy"
            allowed-chars-regex="[\d-]"
            show-calendar-icon="true"
            value="2022-12-22"></ModusDateInput>

          <ModusDateInput
            type="end"
            label="End"
            format="dd-mm-yyyy"
            helper-text="dd-mm-yyyy"
            allowed-chars-regex="[\d-]"
            show-calendar-icon="true"
            value="2022-12-22"></ModusDateInput>
        </ModusDatePicker>
      </div>
    </>
  );
}
