// angular-workspace/test-ng15/src/examples/modus-list-examples/modus-list-examples.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'modus-list-examples',
  template: `
    <h3>List</h3>
    <modus-list>
      <modus-list-item size="condensed">Condensed</modus-list-item>
      <modus-list-item selected size="condensed">Condensed & Selected</modus-list-item>
      <modus-list-item>Default</modus-list-item>
      <modus-list-item selected>Selected</modus-list-item>
      <modus-list-item disabled>Disabled</modus-list-item>
      <modus-list-item size="large">Large</modus-list-item>
      <modus-list-item selected size="large">Large & Selected</modus-list-item>
    </modus-list>
  `,
})
export class ModusListExamplesComponent implements OnInit {
  constructor() {}

  ngOnInit(): void {}
}

// react-workspace/test-react-v19/src/examples/ModusListExamples.tsx
import { ModusList, ModusListItem } from '@trimble-oss/modus-react-components';

export default function ModusListExamples() {
  return (
    <>
      <h3>List</h3>
      <ModusList>
        <ModusListItem size="condensed">Condensed</ModusListItem>
        <ModusListItem selected size="condensed">
          Condensed & Selected
        </ModusListItem>
        <ModusListItem>Default</ModusListItem>
        <ModusListItem selected>Selected</ModusListItem>
        <ModusListItem disabled>Disabled</ModusListItem>
        <ModusListItem size="large">Large</ModusListItem>
        <ModusListItem selected size="large">
          Large & Selected
        </ModusListItem>
      </ModusList>
    </>
  );
}
