// angular-workspace/test-ng14/src/examples/modus-time-picker-examples/modus-time-picker-examples.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'modus-time-picker-examples',
  templateUrl: './modus-time-picker-examples.component.html',
})
export class ModusTimePickerExamplesComponent implements OnInit {
  options = [
    { display: 'Alpha Time Zone' },
    { display: 'Australian Central Daylight Time' },
    { display: 'Atlantic Daylight Time' },
  ];

  constructor() {}

  ngOnInit(): void {}
}

<h3>Time Picker</h3>
<modus-time-picker
  label="Time (Default)"
  placeholder="23:39"
  helper-text="hh:mm"></modus-time-picker>
  <modus-time-picker
  label="Time (12 Hour Format)"
  ampm="true"
  value="23:39"
  placeholder="12:00 AM"
  helper-text="hh:mm AM/PM"></modus-time-picker>
  <modus-time-picker
  ampm="true"
  auto-format="true"
  helper-text="hh:mm AM/PM"
  label="Time (Auto Format)"
  max-length="10"
  placeholder="12:00 AM"></modus-time-picker>
  <modus-time-picker
  helper-text="hh:mm"
  label="Time (Time Picker with Time Zone)"
  max-length="10"
  auto-format="true"
  value="23:39">
  <div style="width: 300px;padding-left: 0.5rem;" slot="timeZone">
    <modus-select
      id="timezone"
      label="Time Zone"
      aria-label="Time Zone"
      options-display-prop="display" [options]="options"></modus-select>
  </div>
</modus-time-picker>

// react-workspace/test-react-v19/src/examples/ModusTimePickerExamples.tsx
import { ModusSelect, ModusTimePicker } from '@trimble-oss/modus-react-components';

export default function ModusTimePickerExamples() {
  return (
    <>
      <h3>Time Picker Input</h3>
      <div className="grid">
        <ModusTimePicker
          ampm={true}
          auto-format="true"
          helper-text="hh:mm AM/PM"
          label="Time"
          max-length="10"
          placeholder="12:00 AM">
          <div style={{ width: '300px', paddingLeft: '0.5rem' }} slot="timeZone">
            <ModusSelect
              id="timezone"
              label="Time Zone"
              aria-label="Time Zone"
              options={[
                { display: 'Alpha Time Zone' },
                { display: 'Australian Central Daylight Time' },
                { display: 'Atlantic Daylight Time' },
              ]}
              options-display-prop="display"></ModusSelect>
          </div>
        </ModusTimePicker>
      </div>
    </>
  );
}
