// angular-workspace/test-ng15/src/examples/modus-dropdown-examples/modus-dropdown-examples.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'modus-dropdown-examples',
  template: `
    <h3>Dropdown</h3>
    <modus-dropdown toggle-element-id="toggleElement">
      <modus-button id="toggleElement" slot="dropdownToggle">Dropdown</modus-button>
      <modus-list slot="dropdownList">
        <modus-list-item size="condensed">Item 1</modus-list-item>
        <modus-list-item size="condensed">Item 2</modus-list-item>
        <modus-list-item size="condensed">Item 3</modus-list-item>
      </modus-list>
    </modus-dropdown>
  `,
})
export class ModusDropdownExamplesComponent implements OnInit {
  constructor() {}

  ngOnInit(): void {}
}

// react-workspace/test-react-v19/src/examples/ModusDropdownExamples.tsx
import { ModusButton, ModusDropdown, ModusList, ModusListItem } from '@trimble-oss/modus-react-components';

export default function ModusDropdownExamples() {
  return (
    <>
      <h3>Dropdown</h3>
      <ModusDropdown toggle-element-id="toggleElement">
        <ModusButton id="toggleElement" slot="dropdownToggle">
          Dropdown
        </ModusButton>
        <ModusList slot="dropdownList">
          <ModusListItem size="condensed">Item 1</ModusListItem>
          <ModusListItem size="condensed">Item 2</ModusListItem>
          <ModusListItem size="condensed">Item 3</ModusListItem>
        </ModusList>
      </ModusDropdown>
    </>
  );
}
