// angular-workspace/test-ng15/src/examples/modus-text-input-examples/modus-text-input-examples.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'modus-text-input-examples',
  templateUrl: './modus-text-input-examples.component.html',
})
export class ModusTextInputExamplesComponent implements OnInit {
  constructor() {}

  ngOnInit(): void {}
}

<h3>Text Inputs</h3>
<modus-text-input
  label="Text Input (Search Icon)"
  placeholder="Placeholder"
  include-search-icon
  required></modus-text-input>
<modus-text-input
  label="Text Input (Search Icon & Disabled)"
  include-search-icon
  disabled></modus-text-input>
<modus-text-input
  label="Text Input (Search Icon & Helper Text)"
  placeholder="Placeholder"
  value="Value"
  helper-text="Helper Demo"
  include-search-icon
  required></modus-text-input>
<modus-text-input
  label="Text Input (Error)"
  placeholder="Placeholder"
  value="Value"
  error-text="Error Demo"></modus-text-input>
<modus-text-input
  label="Text Input (Valid)"
  placeholder="Placeholder"
  value="Value"
  valid-text="Valid Demo"></modus-text-input>
<modus-text-input
  label="Text Input (Large & Helper Text)"
  placeholder="Placeholder"
  value="Value"
  size="large"
  helper-text="Your username must be 8-20 characters long, contain letters and numbers, and must not contain spaces"></modus-text-input>
<modus-text-input
  label="Text Input (Clearable)"
  placeholder="Placeholder"
  value="Value"
  clearable="true"></modus-text-input>
<modus-text-input
  label="Text Input (Password)"
  placeholder="Password"
  type="password"></modus-text-input>

// react-workspace/projects/test-react-v17/src/examples/ModusTextInputExamples.tsx
import { ModusTextInput } from '@trimble-oss/modus-react-components';

export default function ModusTextInputExamples() {
  return (
    <>
      <h3>Text Input</h3>
      <div className="grid">
        <ModusTextInput label="Text Input Demo 1" placeholder="Placeholder" include-search-icon required></ModusTextInput>
        <ModusTextInput label="Text Input Demo 2" include-search-icon disabled></ModusTextInput>
        <ModusTextInput
          label="Text Input Demo 3"
          placeholder="Placeholder"
          value="Value"
          helper-text="Helper Demo"
          include-search-icon
          required></ModusTextInput>
        <ModusTextInput
          label="Text Input Demo 4"
          placeholder="Placeholder"
          value="Value"
          error-text="Error Demo"
          include-search-icon></ModusTextInput>
        <ModusTextInput
          label="Text Input Demo 5"
          placeholder="Placeholder"
          value="Value"
          valid-text="Valid Demo"
          include-search-icon></ModusTextInput>
        <ModusTextInput
          label="Text Input Demo 6"
          placeholder="Placeholder"
          value="Value"
          size="large"
          include-search-icon></ModusTextInput>
        <ModusTextInput label="Text Input Demo 7" placeholder="Placeholder" value="Value" clearable={true}></ModusTextInput>
        <ModusTextInput label="Text Input Demo Password" placeholder="Password" type="password"></ModusTextInput>
      </div>
    </>
  );
}
