// angular-workspace/test-ng14/src/examples/modus-autocomplete-examples/modus-autocomplete-examples.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'modus-autocomplete-examples',
  template: `
    <h3>Autocomplete</h3>
    <div style="width: 500px">
      <modus-autocomplete
        id="default"
        label="Default Autocomplete"
        placeholder="Search..."
        [options]="basicOptions"></modus-autocomplete>

      <modus-autocomplete
        id="with-option"
        label="Autocomplete using option model"
        placeholder="Search..."
        [options]="complexOptions"></modus-autocomplete>

      <modus-autocomplete label="Employee Search" clearable placeholder="Search...">
        <li data-search-value="The Git Guru" data-id="1" style="padding: 8px">
          <div style="font-weight: bold">The Git Guru</div>
          <div style="font-size: 12px">Lead DevOps Engineer</div>
        </li>
        <li data-search-value="Bob the Builder" data-id="2" style="padding: 8px">
          <div style="font-weight: bold">Bob the Builder</div>
          <div style="font-size: 12px">Senior Construction Engineer</div>
        </li>
      </modus-autocomplete>
    </div>
  `,
})
export class ModusAutocompleteExamplesComponent implements OnInit {
  basicOptions = ['Apple', 'Banana', 'Orange'];
  complexOptions = [
    { id: '0', value: 'Apple' },
    { id: '1', value: 'Banana' },
    { id: '2', value: 'Orange' },
  ];
  constructor() {}

  ngOnInit(): void {}
}

// react-workspace/projects/test-react-v17/src/examples/ModusAutoCompleteExamples.tsx
import { ModusAutocomplete } from '@trimble-oss/modus-react-components';

export default function ModusAutoCompleteExamples() {
  return (
    <>
      <h3>AutoComplete</h3>
      <div className="grid">
        <div style={{ width: '500px' }}>
          <ModusAutocomplete
            id="default"
            options={['Apple', 'Banana', 'Orange']}
            label="Default Autocomplete"
            placeholder="Search..."></ModusAutocomplete>

          <ModusAutocomplete
            id="with-option"
            options={[
              { id: '0', value: 'Apple' },
              { id: '1', value: 'Banana' },
              { id: '2', value: 'Orange' },
            ]}
            label="Autocomplete using option model"
            placeholder="Search..."></ModusAutocomplete>

          <ModusAutocomplete label="Employee Search" clearable placeholder="Search...">
            <li data-search-value="The Git Guru" data-id="1" style={{ padding: '8px' }}>
              <div style={{ fontWeight: 'bold' }}>The Git Guru</div>
              <div style={{ fontSize: '12px' }}>Lead DevOps Engineer</div>
            </li>
            <li data-search-value="Bob the Builder" data-id="2" style={{ padding: '8px' }}>
              <div style={{ fontWeight: 'bold' }}>Bob the Builder</div>
              <div style={{ fontSize: '12px' }}>Senior Construction Engineer</div>
            </li>
          </ModusAutocomplete>
        </div>
      </div>
    </>
  );
}
