// angular-workspace/test-ng14/src/examples/modus-chip-examples/modus-chip-examples.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'modus-chip-examples',
  template: `
    <h3>Chips</h3>
    <modus-chip image-url="https://example.com/image.jpg" show-close value="Bryan"></modus-chip>
    <modus-chip has-error image-url="https://example.com/image.jpg" show-close value="Bryan"></modus-chip>
    <modus-chip disabled image-url="https://example.com/image.jpg" show-close value="Bryan"></modus-chip>

    <modus-chip image-url="https://example.com/image.jpg" show-close chip-style="outline" value="Bryan"></modus-chip>
    <modus-chip
      has-error
      image-url="https://example.com/image.jpg"
      show-close
      chip-style="outline"
      value="Bryan"></modus-chip>
    <modus-chip
      disabled
      image-url="https://example.com/image.jpg"
      show-close
      chip-style="outline"
      value="Bryan"></modus-chip>

    <modus-chip show-checkmark size="small" value="Pets OK"></modus-chip>
  `,
})
export class ModusChipExamplesComponent implements OnInit {
  constructor() {}

  ngOnInit(): void {}
}

// react-workspace/projects/test-react-v17/src/examples/ModusChipExamples.tsx
import { ModusChip } from '@trimble-oss/modus-react-components';

export default function ModusChipExamples() {
  return (
    <>
      <h3>Chips</h3>
      <div className="grid-row">
        <ModusChip image-url="https://example.com/image.jpg" show-close value="Bryan"></ModusChip>
        <ModusChip has-error image-url="https://example.com/image.jpg" show-close value="Bryan"></ModusChip>
        <ModusChip disabled image-url="https://example.com/image.jpg" show-close value="Bryan"></ModusChip>
      </div>
      <div className="grid-row">
        <ModusChip image-url="https://example.com/image.jpg" show-close chip-style="outline" value="Bryan"></ModusChip>
        <ModusChip
          has-error
          image-url="https://example.com/image.jpg"
          show-close
          chip-style="outline"
          value="Bryan"></ModusChip>
        <ModusChip
          disabled
          image-url="https://example.com/image.jpg"
          show-close
          chip-style="outline"
          value="Bryan"></ModusChip>
      </div>
      <div className="grid-row">
        <ModusChip show-checkmark size="small" value="Pets OK"></ModusChip>
      </div>
    </>
  );
}
