// angular-workspace/test-ng15/src/examples/modus-spinner-examples/modus-spinner-examples.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'modus-spinner-examples',
  template: `
    <h3>Spinner</h3>
    <div style="display: flex; flex-direction:column; gap:20px;">
      <!-- Spinner -->
      <modus-spinner></modus-spinner>

      <modus-spinner color="secondary"></modus-spinner>

      <modus-spinner color="tertiary"></modus-spinner>

      <!-- Render in another element with different color and size -->
      <modus-button color="primary" disabled>
        <modus-spinner color="white" size=".5rem"></modus-spinner>
        &nbsp;Loading...
      </modus-button>
    </div>
  `,
})
export class ModusSpinnerExamplesComponent implements OnInit {
  constructor() {}

  ngOnInit(): void {}
}

// react-workspace/projects/test-react-v17/src/examples/ModusSpinnerExamples.tsx
import { ModusButton, ModusSpinner } from '@trimble-oss/modus-react-components';

export default function ModusSpinnerExamples() {
  return (
    <>
      <h3>Spinner</h3>
      <ModusSpinner></ModusSpinner>
      <ModusSpinner color="secondary"></ModusSpinner>
      <ModusButton color="primary" disabled>
        <ModusSpinner color="white" size=".5rem"></ModusSpinner>
        &nbsp;Loading...
      </ModusButton>
    </>
  );
}
