// react-workspace/test-react-v17/src/examples/ModusTooltipExamples.tsx
import { ModusButton, ModusTooltip } from '@trimble-oss/modus-react-components';

export default function ModusToolTipExamples() {
  return (
    <>
      <h3>Tooltips</h3>
      <ModusTooltip text="Tooltip text..." position="right">
        <ModusButton>Button</ModusButton>
      </ModusTooltip>
    </>
  );
}

// angular-workspace/test-ng15/src/examples/modus-tooltip-examples/modus-tooltip-examples.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'modus-tooltip-examples',
  template: `
    <h3>Tooltip</h3>
    <modus-tooltip text="Tooltip text..." position="right">
      <modus-button>Button</modus-button>
    </modus-tooltip>
  `,
})
export class ModusTooltipExamplesComponent implements OnInit {
  constructor() {}

  ngOnInit(): void {}
}
