// react-workspace/test-react-v17/src/examples/ModusToastExamples.tsx
import { ModusToast } from '@trimble-oss/modus-react-components';

export default function ModusToastExamples() {
  return (
    <>
      <h3>Toasts</h3>
      <div className="grid">
        <ModusToast type="default">Default</ModusToast>
        <ModusToast type="danger">Danger</ModusToast>
        <ModusToast type="dark">Dark</ModusToast>
        <ModusToast type="primary">Primary</ModusToast>
        <ModusToast type="secondary">Secondary</ModusToast>
        <ModusToast type="success">Success</ModusToast>
        <ModusToast type="warning">Warning</ModusToast>
      </div>
    </>
  );
}

// angular-workspace/test-ng15/src/examples/modus-toast-examples/modus-toast-examples.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'modus-toast-examples',
  template: ` <h3>Toasts</h3>
    <div style="display: flex; flex-direction:column; gap:20px;">
      <modus-toast type="default">Default</modus-toast>
      <modus-toast type="danger">Danger</modus-toast>
      <modus-toast type="dark">Dark</modus-toast>
      <modus-toast type="primary">Primary</modus-toast>
      <modus-toast type="secondary">Secondary</modus-toast>
      <modus-toast type="success">Success</modus-toast>
      <modus-toast type="warning">Warning</modus-toast>
    </div>`,
})
export class ModusToastExamplesComponent implements OnInit {
  constructor() {}

  ngOnInit(): void {}
}
