// angular-workspace/test-ng15/src/examples/modus-checkbox-examples/modus-checkbox-examples.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'modus-checkbox-examples',
  template: `
    <h3>Checkbox</h3>
    <modus-checkbox></modus-checkbox>
    <modus-checkbox disabled></modus-checkbox>
    <modus-checkbox label="Checkbox"></modus-checkbox>
    <modus-checkbox disabled label="Checkbox"></modus-checkbox>
    <modus-checkbox checked disabled label="Checkbox"></modus-checkbox>
    <modus-checkbox indeterminate></modus-checkbox>
  `,
})
export class ModusCheckboxExamplesComponent implements OnInit {
  constructor() {}

  ngOnInit(): void {}
}

// react-workspace/test-react-v18/src/examples/ModusCheckboxExamples.tsx
import { ModusCheckbox } from '@trimble-oss/modus-react-components';

export default function ModusCheckboxExamples() {
  return (
    <>
      <h3>Checkbox</h3>
      <div className="grid">
        <ModusCheckbox></ModusCheckbox>
        <ModusCheckbox disabled></ModusCheckbox>
        <ModusCheckbox label="Checkbox"></ModusCheckbox>
        <ModusCheckbox disabled label="Checkbox"></ModusCheckbox>
        <ModusCheckbox checked disabled label="Checkbox"></ModusCheckbox>

        <ModusCheckbox indeterminate></ModusCheckbox>
      </div>
    </>
  );
}
