// angular-workspace/test-ng14/src/examples/modus-select-examples/modus-select-examples.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'modus-select-examples',
  templateUrl: './modus-select-examples.component.html',
})
export class ModusSelectExamplesComponent implements OnInit {
  options = [{ display: 'Option 1' }, { display: 'Option 2' }, { display: 'Option 3' }];
  handleChange = (event: any) => {
    const selectedValue = event.detail;
    event.target.value = selectedValue;
  };

  selectedValue = { display: 'Option 1' };

  constructor() {}

  ngOnInit(): void {}
}

<h3>Select Input</h3>
<div class="flex-column">
  <!-- Without preset value -->
<modus-select
id="select-demo-1"
label="Select Demo 1"
options-display-prop="display" [options]="options" (valueChange)="handleChange($event)"  ></modus-select>

<!-- Disabled with helper text and preset value -->
<modus-select
disabled
helper-text="Helper demo"
id="select-demo-2"
label="Select Demo 2"
options-display-prop="display" [value]="selectedValue" [options]="options"></modus-select>

<!-- Error -->
<modus-select error-text="Error demo"  [options]="options" label="Select Demo 3"></modus-select>

<!-- Valid -->
<modus-select label="Select Demo 4"  [options]="options" valid-text="Valid demo"></modus-select>

<!-- 'Large select -->
<modus-select
id="select-demo-5"
label="Select Demo 5"
size="large"
options-display-prop="display"  [options]="options"></modus-select>
</div>

// react-workspace/test-react-v17/src/examples/ModusSelectExamples.tsx
import { ModusSelect } from '@trimble-oss/modus-react-components';

export default function ModusSelectExamples() {
  return (
    <>
      <h3>Select Input</h3>
      <div className="grid">
        <ModusSelect
          id="select-demo-1"
          label="Select Demo 1"
          value={{ display: 'Option 1' }}
          options-display-prop="display"
          options={[{ display: 'Option 1' }, { display: 'Option 2' }, { display: 'Option 3' }]}></ModusSelect>

        <ModusSelect
          disabled
          helper-text="Helper demo"
          id="select-demo-2"
          label="Select Demo 2"
          options-display-prop="display"></ModusSelect>

        <ModusSelect error-text="Error demo" label="Select Demo 3"></ModusSelect>

        <ModusSelect label="Select Demo 4" value="Option 1" valid-text="Valid demo"></ModusSelect>
      </div>
    </>
  );
}
