// angular-workspace/test-ng15/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent {
  title = 'modus-angular-test-0.1.40-ng14';

  themeToggleClick(e: any) {
    const theme = window.document?.firstElementChild?.getAttribute('data-mwc-theme') === 'dark' ? 'light' : 'dark';
    window.document?.firstElementChild?.setAttribute('data-mwc-theme', theme);
  }
}



<div class="theme-toggle-switch">
  <modus-switch
    label="
Toggle Theme"
    (switchClick)="themeToggleClick($event)"></modus-switch>
</div>
<div class="grid w-50">
  <modus-accordion-examples></modus-accordion-examples>
  <modus-alert-examples></modus-alert-examples>
  <modus-autocomplete-examples></modus-autocomplete-examples>
  <modus-badge-examples></modus-badge-examples>
  <modus-breadcrumb-examples></modus-breadcrumb-examples>
  <modus-button-examples></modus-button-examples>
  <modus-card-examples></modus-card-examples>
  <modus-checkbox-examples></modus-checkbox-examples>
  <modus-chip-examples></modus-chip-examples>
  <modus-content-tree-examples></modus-content-tree-examples>
  <modus-data-table-examples></modus-data-table-examples>
  <modus-date-picker-examples></modus-date-picker-examples>
  <modus-dropdown-examples></modus-dropdown-examples>
  <modus-file-dropzone-examples></modus-file-dropzone-examples>
  <modus-list-examples></modus-list-examples>
  <modus-message-examples></modus-message-examples>
  <modus-modal-examples></modus-modal-examples>
  <modus-navbar-examples></modus-navbar-examples>
  <modus-number-examples></modus-number-examples>
  <modus-pagination-examples></modus-pagination-examples>
  <modus-progress-bar-examples></modus-progress-bar-examples>
  <modus-radio-group-examples></modus-radio-group-examples>
  <modus-select-examples></modus-select-examples>
  <modus-side-navigation-examples></modus-side-navigation-examples>
  <modus-slider-examples></modus-slider-examples>
  <modus-spinner-examples></modus-spinner-examples>
  <modus-switch-examples></modus-switch-examples>
  <modus-tabs-examples></modus-tabs-examples>
  <modus-text-input-examples></modus-text-input-examples>
  <modus-time-picker-examples></modus-time-picker-examples>
  <modus-toast-examples></modus-toast-examples>
  <modus-tooltip-examples></modus-tooltip-examples>
</div>

// react-workspace/test-react-v17/src/App.tsx
import React from 'react';
import './App.css';
import * as ModusReactExamples from './examples';
import { ModusSwitch } from '@trimble-oss/modus-react-components';

function App() {
  return (
    <>
      <div className="theme-toggle-switch">
        <ModusSwitch
          label="
    Toggle Theme"
          onSwitchClick={(e: any) => {
            const theme = window.document?.firstElementChild?.getAttribute('data-mwc-theme') === 'dark' ? 'light' : 'dark';
            window.document?.firstElementChild?.setAttribute('data-mwc-theme', theme);
          }}></ModusSwitch>
      </div>
      <div className="grid w-50">
        <ModusReactExamples.Accordion />
        <ModusReactExamples.Alert />
        <ModusReactExamples.Badge />
        <ModusReactExamples.Breadcrumb />
        <ModusReactExamples.Button />
        <ModusReactExamples.Card />
        <ModusReactExamples.Chip />
        <ModusReactExamples.ContentTree />
        <ModusReactExamples.DataTable />
        <ModusReactExamples.Dropdown />
        <ModusReactExamples.FileDropZone />
        <ModusReactExamples.FloatingNavbar />
        <ModusReactExamples.List />
        <ModusReactExamples.Message />
        <ModusReactExamples.Modal />
        <ModusReactExamples.Pagination />
        <ModusReactExamples.Navbar />
        <ModusReactExamples.ProgressBar />
        <ModusReactExamples.RadioGroup />
        <ModusReactExamples.SideNavigation />
        <ModusReactExamples.Slider />
        <ModusReactExamples.Spinner />
        <ModusReactExamples.Tab />
        <ModusReactExamples.Toast />
        <ModusReactExamples.Tooltip />
        <ModusReactExamples.AutoComplete />
        <ModusReactExamples.Checkbox />
        <ModusReactExamples.DatePicker />
        <ModusReactExamples.NumberInput />
        <ModusReactExamples.Select />
        <ModusReactExamples.Switch />
        <ModusReactExamples.TextInput />
        <ModusReactExamples.TimePicker />
        <ModusReactExamples.Table />
      </div>
    </>
  );
}

export default App;
