// react-workspace/test-react-v18/src/examples/ModusBadgeExamples.tsx
import { ModusBadge } from '@trimble-oss/modus-react-components';

export default function ModusBadgeExamples() {
  return (
    <>
      <h3>Badge</h3>
      <div className="grid">
        <div className="grid-row">
          <ModusBadge>Default</ModusBadge>
          <ModusBadge color="secondary">Secondary</ModusBadge>
          <ModusBadge color="tertiary">Tertiary</ModusBadge>
          <ModusBadge color="dark">Dark</ModusBadge>
          <ModusBadge color="warning">Warning</ModusBadge>
          <ModusBadge color="danger">Danger</ModusBadge>
        </div>

        <div className="grid-row">
          <ModusBadge size="small">Small</ModusBadge>
          <ModusBadge size="medium">Medium</ModusBadge>
          <ModusBadge size="large">Large</ModusBadge>
        </div>

        <div className="grid-row">
          <ModusBadge type="counter">Counter</ModusBadge>
          <ModusBadge color="secondary" type="counter">
            Counter
          </ModusBadge>
          <ModusBadge color="tertiary" type="counter">
            Counter
          </ModusBadge>
          <ModusBadge color="dark" type="counter">
            Counter
          </ModusBadge>
          <ModusBadge color="warning" type="counter">
            Counter
          </ModusBadge>
          <ModusBadge color="danger" type="counter">
            Counter
          </ModusBadge>
        </div>

        <div className="grid-row">
          <ModusBadge size="small" type="counter">
            Small
          </ModusBadge>
          <ModusBadge size="medium" type="counter">
            Medium
          </ModusBadge>
          <ModusBadge size="large" type="counter">
            Large
          </ModusBadge>
        </div>

        <div className="grid-row">
          <ModusBadge type="text">Primary</ModusBadge>
          <ModusBadge color="secondary" type="text">
            Secondary
          </ModusBadge>
          <ModusBadge color="dark" type="text">
            High Contrast
          </ModusBadge>
          <ModusBadge color="success" type="text">
            Success
          </ModusBadge>
          <ModusBadge color="danger" type="text">
            Danger
          </ModusBadge>
        </div>

        <div className="grid-row">
          <ModusBadge size="small" type="text">
            Small
          </ModusBadge>
          <ModusBadge size="medium" type="text">
            Medium
          </ModusBadge>
          <ModusBadge size="large" type="text">
            Large
          </ModusBadge>
        </div>
      </div>
    </>
  );
}

// angular-workspace/test-ng15/src/examples/modus-badge-examples/modus-badge-examples.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'modus-badge-examples',
  template: `
    <h3>Badges</h3>
    <div class="flex-column">
      <div class="flex-row">
        <modus-badge>Default</modus-badge>
        <modus-badge color="secondary">Secondary</modus-badge>
        <modus-badge color="tertiary">Tertiary</modus-badge>
        <modus-badge color="dark">Dark</modus-badge>
        <modus-badge color="warning">Warning</modus-badge>
        <modus-badge color="danger">Danger</modus-badge>
      </div>

      <div class="flex-row">
        <modus-badge size="small">Small</modus-badge>
        <modus-badge size="medium">Medium</modus-badge>
        <modus-badge size="large">Large</modus-badge>
      </div>

      <div class="flex-row">
        <modus-badge type="counter">Counter</modus-badge>
        <modus-badge color="secondary" type="counter">Counter</modus-badge>
        <modus-badge color="tertiary" type="counter">Counter</modus-badge>
        <modus-badge color="dark" type="counter">Counter</modus-badge>
        <modus-badge color="warning" type="counter">Counter</modus-badge>
        <modus-badge color="danger" type="counter">Counter</modus-badge>
      </div>

      <div class="flex-row">
        <modus-badge size="small" type="counter">Small</modus-badge>
        <modus-badge size="medium" type="counter">Medium</modus-badge>
        <modus-badge size="large" type="counter">Large</modus-badge>
      </div>

      <div class="flex-row">
        <modus-badge type="text">Primary</modus-badge>
        <modus-badge color="secondary" type="text">Secondary</modus-badge>
        <modus-badge color="dark" type="text">High Contrast</modus-badge>
        <modus-badge color="success" type="text">Success</modus-badge>
        <modus-badge color="danger" type="text">Danger</modus-badge>
      </div>

      <div class="flex-row">
        <modus-badge size="small" type="text">Small</modus-badge>
        <modus-badge size="medium" type="text">Medium</modus-badge>
        <modus-badge size="large" type="text">Large</modus-badge>
      </div>
    </div>
  `,
})
export class ModusBadgeExamplesComponent implements OnInit {
  constructor() {}

  ngOnInit(): void {}
}
