// react-workspace/test-react-v19/src/examples/ModusButtonExamples.tsx
import { ModusButton } from '@trimble-oss/modus-react-components';

export default function ModusButtonExamples() {
  return (
    <>
      <h3>Buttons</h3>
      <div className="grid-row">
        <ModusButton color="primary">Primary</ModusButton>
        <ModusButton color="secondary">Secondary</ModusButton>
        <ModusButton color="tertiary">Tertiary</ModusButton>
      </div>
      <div className="grid-row">
        <ModusButton color="danger">Danger</ModusButton>
        <ModusButton disabled color="danger">
          Disabled
        </ModusButton>
      </div>
      <div className="grid-row">
        <ModusButton size="small" color="primary">
          Small
        </ModusButton>
        <ModusButton size="large" color="primary">
          Large
        </ModusButton>
      </div>
      <div className="grid-row">
        <ModusButton button-style="borderless">Borderless</ModusButton>
      </div>
      <div className="grid-row">
        <ModusButton button-style="outline" color="primary">
          Outline
        </ModusButton>
        <ModusButton button-style="outline" color="secondary">
          Outline
        </ModusButton>
      </div>
    </>
  );
}

// angular-workspace/test-ng15/src/examples/modus-button-examples/modus-button-examples.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'modus-button-examples',
  template: `
    <h3>Buttons</h3>
    <div class="flex-column">
      <div class="flex-row">
        <modus-button color="primary">Primary</modus-button>
        <modus-button color="secondary">Secondary</modus-button>
        <modus-button color="tertiary">Tertiary</modus-button>
      </div>

      <div class="flex-row">
        <modus-button color="danger">Danger</modus-button>
        <modus-button disabled color="danger">Disabled</modus-button>
      </div>

      <div class="flex-row">
        <modus-button size="small" color="primary">Small</modus-button>
        <modus-button size="large" color="primary">Large</modus-button>
      </div>

      <div class="flex-row">
        <modus-button button-style="borderless">Borderless</modus-button>
      </div>

      <div class="flex-row">
        <modus-button button-style="outline" color="primary">Outline</modus-button>
        <modus-button button-style="outline" color="secondary">Outline</modus-button>
      </div>
    </div>
  `,
})
export class ModusButtonExamplesComponent implements OnInit {
  constructor() {}

  ngOnInit(): void {}
}
